//! .

mod bidiff;
mod bipatch;
mod files_diff;
mod mmap_io;

use std::path::Path;

pub use files_diff::{CompressAlgorithm, PatchMetadata, Result};
pub use mmap_io::{MmapReader, MmapWriter};

pub(crate) const MAGIC: u32 = 0xB1DF;
pub(crate) const VERSION: u32 = 0x1000;

/// Generates a patch between two files using specified algorithms.
///
/// Creates a patch that can transform the `before` data into the `after` data,
/// using the specified diff and compression algorithms. The patch is stored
/// to the given patch_path.
///
/// # Example
/// ```rust
/// use std::path::Path;
/// use mmap_bidiff::{diff, CompressAlgorithm};
///
/// let before = Path::new("original.bin");
/// let after = Path::new("modified.bin");
/// let patch = Path::new("patch.bin");
///
/// let meta = diff(
///     before,
///     after,
///     patch_path,
///     CompressAlgorithm::Zstd
/// )?;
/// # Ok::<(), mmap_bidiff::Error>(())
/// ```
pub fn diff(
    before: &Path,
    after: &Path,
    patch_path: &Path,
    compress_algorithm: CompressAlgorithm,
) -> Result<PatchMetadata> {
    files_diff::diff(before, after, patch_path, compress_algorithm)
}

/// Applies a patch to transform the base data.
///
/// Takes a patch generated by `diff()` and applies it to the base data
/// to recreate the target data.
///
/// # Example
/// ```rust
/// use mmap_bidiff::{self, CompressAlgorithm};
/// use std::fs::File;
/// use std::io::Write;
/// use std::path::Path;
///
/// // Prepare files
/// let before = Path::new("original.bin");
/// let after = Path::new("modified.bin");
/// let patch = Path::new("patch.bin");
/// let result = Path::new("reconstructed.bin");
///
/// File::create(before)?.write_all(b"hello world")?;
/// File::create(after)?.write_all(b"hello mars")?;
///
/// // Create patch
/// let _meta = mmap_bidiff::diff(before, after, patch, CompressAlgorithm::Zstd)?;
///
/// // Apply patch
/// mmap_bidiff::apply(before, patch, result)?;
///
/// // Assert equality
/// let expected = fs::read(after)?;
/// let actual = fs::read(result)?;
/// assert_eq!(actual, expected);
///
/// # Ok::<(), mmap_bidiff::Error>(())
/// ```
pub fn apply(base: &Path, patch: &Path, output: &Path) -> Result<()> {
    files_diff::apply(base, patch, output)
}

/// Generates an MD5 hash of the provided data as a hexadecimal string.
///
/// This function is used internally for patch validation to ensure data
/// integrity.
///
/// # Example
/// ```rust
/// use mmap_bidiff::hash;
///
/// let data = b"Hello, world!";
/// let hash_str = hash(data);
/// assert_eq!(hash_str.len(), 32); // MD5 hash is always 32 hex chars
/// ```
pub fn hash(data: &[u8]) -> String {
    files_diff::hash(data)
}
